package org.lzn.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-06T16:01:50.121+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "WeatherService",
                  wsdlLocation = "http://127.0.0.1:12345/weather?wsdl",
                  targetNamespace = "http://service.lzn.org/")
public class WeatherService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.lzn.org/", "WeatherService");
    public final static QName WeatherPort = new QName("http://service.lzn.org/", "WeatherPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:12345/weather?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WeatherService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:12345/weather?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WeatherService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WeatherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WeatherService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WeatherService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WeatherService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Weather
     */
    @WebEndpoint(name = "WeatherPort")
    public Weather getWeatherPort() {
        return super.getPort(WeatherPort, Weather.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Weather
     */
    @WebEndpoint(name = "WeatherPort")
    public Weather getWeatherPort(WebServiceFeature... features) {
        return super.getPort(WeatherPort, Weather.class, features);
    }

}
