
package org.lzn.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherImplService", targetNamespace = "http://impl.service.lzn.org/", wsdlLocation = "http://127.0.0.1:12345/weather?wsdl")
public class WeatherImplService
    extends Service
{

    private final static URL WEATHERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEATHERIMPLSERVICE_EXCEPTION;
    private final static QName WEATHERIMPLSERVICE_QNAME = new QName("http://impl.service.lzn.org/", "WeatherImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12345/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERIMPLSERVICE_WSDL_LOCATION = url;
        WEATHERIMPLSERVICE_EXCEPTION = e;
    }

    public WeatherImplService() {
        super(__getWsdlLocation(), WEATHERIMPLSERVICE_QNAME);
    }

    public WeatherImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERIMPLSERVICE_QNAME, features);
    }

    public WeatherImplService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERIMPLSERVICE_QNAME);
    }

    public WeatherImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERIMPLSERVICE_QNAME, features);
    }

    public WeatherImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherImpl
     */
    @WebEndpoint(name = "WeatherImplPort")
    public WeatherImpl getWeatherImplPort() {
        return super.getPort(new QName("http://impl.service.lzn.org/", "WeatherImplPort"), WeatherImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherImpl
     */
    @WebEndpoint(name = "WeatherImplPort")
    public WeatherImpl getWeatherImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.lzn.org/", "WeatherImplPort"), WeatherImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERIMPLSERVICE_EXCEPTION!= null) {
            throw WEATHERIMPLSERVICE_EXCEPTION;
        }
        return WEATHERIMPLSERVICE_WSDL_LOCATION;
    }

}
